#!/usr/bin/env bash

set -e

pip install "$(grep '^uv' < requirements_test.txt)"
uv venv
uv pip install -U "pip>=21.3.1" setuptools wheel
uv pip install -r requirements_test.txt
uv run --no-project -m pytest tests
