#!/usr/bin/env bash

set -e

pip install "$(grep '^uv' < requirements_test.txt)"
uv venv
uv pip install -U "pip>=21.3.1" setuptools wheel
requirements=(-r requirements_test.txt)
if [[ -n "${AIOFILES_VERSION:-}" ]]; then
    requirements+=("aiofiles==${AIOFILES_VERSION}")
fi
uv pip install "${requirements[@]}"
uv run --no-project -m pytest tests
